### ISSUE TITLE
Still need, create, edit, and delete functionality

### ISSUE THREAD

**Issue by phaugland** [3900860s20team2/canvas-lite#13]
Hey Levi, 

I noticed that the pages for create, delete and edit were still placeholders or didn't exist so I figured I'd drop this issue to help track them. 

Thanks, 

Patrick H.

**Comment by leviprice97** [comment]
The capabilities to create, edit, and delete an announcement have now been updated.

**Comment by phaugland** [comment]
code is merged to master.
